---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-max-fedora
    image: fedora:37

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-max/converge.yml

scenario:
  name: fedora-cm-max

verifier:
  name: testinfra
  directory: ../cm-max/tests
