---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-debian-max
    image: debian:11

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-max/converge.yml

scenario:
  name: debian-max-cm-max

verifier:
  name: testinfra
  directory: ../cm-max/tests
