---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-camundamodeler
      cm_download_url: https://github.com/camunda/camunda-modeler/releases/download/v5.6.0
      plugins:
        - name: tooltip
          url: https://github.com/viadee/camunda-modeler-tooltip-plugin/archive/refs/tags/v0.0.8.tar.gz
        - name: token-simulation
          url: https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/archive/refs/heads/master.zip

  post_tasks:
    - name: verify camundamodeler facts
      assert:
        that:
          - ansible_local.camundamodeler.general.version == '5.6.0'
          - ansible_local.camundamodeler.general.home == '/opt/camunda-modeler/5.6.0'
