---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-ubuntu-max
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

scenario:
  name: ubuntu-max-cm-max

verifier:
  name: testinfra
  directory: ../cm-max/tests
