---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-camunda-modeler
      cm_download_url: https://downloads.camunda.cloud/release/camunda-modeler/4.5.0

  post_tasks:
    - name: verify camunda-modeler facts
      assert:
        that:
          - ansible_local.camundamodeler.general.version == '4.5.0'
          - ansible_local.camundamodeler.general.home == '/opt/camunda-modeler/4.5.0'
