---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-camundamodeler
      cm_download_url: https://github.com/camunda/camunda-modeler/releases/download/v4.12.0

  post_tasks:
    - name: verify camundamodeler facts
      assert:
        that:
          - ansible_local.camundamodeler.general.version == '4.12.0'
          - ansible_local.camundamodeler.general.home == '/opt/camunda-modeler/4.12.0'
