---
- name: Load version vars
  with_first_found:
    - '../vars/versions/{{ cm_version }}.yml'
    - ../vars/versions/main.yml
  include_vars: '{{ item }}'

- name: Assert version vars
  ansible.builtin.assert:
    that:
      - "cm_redis_sha256sum not in (None, '')"

- name: Create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ cm_download_dir }}'

- name: Download Camunda-Modeler
  ansible.builtin.get_url:
    url: '{{ cm_download_url }}/{{ cm_redis_filename }}'
    dest: '{{ cm_download_dir }}/{{ cm_redis_filename }}'
    checksum: 'sha256:{{ cm_redis_sha256sum }}'
    force: no
    mode: 'u=rw,go=r'

- name: "Create {{ cm_install_dir }} installation directory"
  become: yes
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ cm_install_dir }}'

- name: Install unarchive dependencies
  become: yes
  ansible.builtin.package:
    name:
      - gzip
      - tar
      - unzip
    state: present

- name: Install Camunda-Modeler
  become: yes
  ansible.builtin.unarchive:
    src: '{{ cm_download_dir }}/{{ cm_redis_filename }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    dest: '{{ cm_install_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

# Set Camunda-Modeler facts
- name: Create Ansible facts.d directory
  become: yes
  ansible.builtin.file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: Install Camunda-Modeler facts
  become: yes
  ansible.builtin.template:
    src: facts.j2
    dest: /etc/ansible/facts.d/camundamodeler.fact
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: Re-read facts
  ansible.builtin.setup:
    filter: ansible_local

- name: Install Camunda-Modeler link
  become: yes
  ansible.builtin.file:
    state: link
    src: '{{ cm_install_dir }}/camunda-modeler'
    dest: '/usr/local/bin/camunda-modeler'

- name: Install Camunda-Modeler desktop file
  become: yes
  ansible.builtin.template:
    src: camunda-modeler.desktop.j2
    dest: '/usr/share/applications/camunda-modeler.desktop'
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: Install plugins
  ansible.builtin.include_tasks: plugins.yaml
  when: (plugins is defined)
