---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-ubuntu-max
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-min/converge.yml

scenario:
  name: ubuntu-max-cm-min

verifier:
  name: testinfra
  directory: ../cm-min/tests
