---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-cm-ubuntu-max
    image: ubuntu:20.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-min/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-max-cm-min

verifier:
  name: testinfra
  directory: ../cm-min/tests
  lint:
    name: flake8
