---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-debian-min
    image: debian:9

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-min/converge.yml

scenario:
  name: debian-min-cm-min

verifier:
  name: testinfra
  directory: ../cm-min/tests
