---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-camundamodeler

  post_tasks:
    - name: verify camundamodeler facts
      assert:
        that:
          - ansible_local.camundamodeler.general.version == '5.8.0'
          - ansible_local.camundamodeler.general.home == '/opt/camunda-modeler/5.8.0'

    - name: install find - required for tests (dnf)
      dnf:
        name:
          - findutils
          - which
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: install which - required for tests (zypper)
      zypper:
        name:
          - which
        state: present
      when: ansible_pkg_mgr == 'zypper'