---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-camundamodeler

  post_tasks:
    - name: verify camundamodeler facts
      assert:
        that:
          - ansible_local.camundamodeler.general.version == '4.6.0'
          - ansible_local.camundamodeler.general.home == '/opt/camunda-modeler/4.6.0'
