---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-cm-opensuse
    image: opensuse/leap:15.4

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-max/converge.yml

scenario:
  name: opensuse-cm-max

verifier:
  name: testinfra
  directory: ../cm-max/tests
